### ISSUE TITLE
How to use AWS credentials instead of profiles?

### ISSUE THREAD

**Issue by tomkeysers** [UnlyEd/airtable-backups-boilerplate#12]
The serverless.yml on lines 25 and 28 says `replace by your own serverless profile, or provide AWS credentials directly if you don't use profiles` -- but how exactly do you do that? It's not clear to me what I have to fill in instead.

(yeah, pretty new to AWS :))

**Comment by Vadorequest** [comment]
Here is the official documentation for Profiles, that's what I recommend using.

I usually write those files by hand, but it's also doable through the CLI.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
